# -*- coding: utf-8 -*-
"""Deployment of Malaria Disease model on Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XHFqww5F09xCMy7tvWzwcScBADFMRYIE
"""

!pip install streamlit

!pip install pyngrok==4.1.1

# Commented out IPython magic to ensure Python compatibility.
# %%writefile malaria.py
# import streamlit as st
# import numpy as np
# import tensorflow as tf
# 
# @st.cache(allow_output_mutation = True)
# 
# def load_model():
#   model = tf.keras.models.load_model("/content/drive/MyDrive/Malaria_dataset/malaria_dataset/malaria_model_vgg19.h5")
#   return model
# 
# model = load_model()
# st.write("# Malaria Disease Classification")
# 
# file = st.file_uploader("Please upload an malaria cell image", type=['jpg', 'png'])
# from PIL import Image, ImageOps
# def import_and_predict(image_data, model):
#   size = (224, 224)
#   image = ImageOps.fit(image_data, size, Image.ANTIALIAS)
#   img = np.asarray(image)
#   img = img/255.0
#   img_reshape = img[np.newaxis,...]
#   prediction = model.predict(img_reshape)
# 
#   return prediction
# 
# if file is None:
#   st.text("Please upload an image file..")
# 
# else:
#   image = Image.open(file)
#   st.image(image, use_column_width = True)
#   predictions = import_and_predict(image, model)
#   class_names = ['Infected', 'Uninfected']
# 
#   if np.argmax(predictions) == 1:
#     st.write("Great!!!, You don't have malaria disease.")
# 
#   else:
#     st.write("Sorry,You have malaria disease,kindly contact your doctor.")
# 
#

!ngrok authtoken 1lWUdS0U3Wx3MIr4kaaXKD5EXA0_5W93S5b4a7cUSx1bD8wdp

!nohup streamlit run malaria.py &

from pyngrok import ngrok
public_url = ngrok.connect(port = '8501')

public_url

!cat /content/nohup.out

ngrok.kill()

































